baseURL = "" #"http://avihaybar.github.io/unsorted.dev/"
languageCode = 'en-us'
theme = 'coming-soon'

[params]
    title = 'unsorted.dev'
    description = 'Avihay Bar'
    release = 'March 01, 2024'
    socialIcons = [
        {name = "email", url = "avihaybar@gmail.com"},
        {name = "github", url = "https://github.com/avihaybar"},
        {name = "linkedin", url = "https://www.linkedin.com/in/avihaybar"},
    ]

